# Generated by Django 5.1 on 2025-03-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama hanya boleh mengandung huruf, angka, dan karakter . _ -', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField(help_text='Usia minimal 12 tahun')),
                ('nomor_hp', models.CharField(help_text='Format: kode negara - nomor telepon (minimal 8, maksimal 15 angka)', max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('url_blog', models.URLField(max_length=255)),
                ('deskripsi_diri', models.TextField(help_text='Minimal 5, maksimal 1000 karakter', max_length=1000)),
                ('npm', models.CharField(help_text='NPM harus 10 digit angka.', max_length=10, unique=True)),
                ('ipk', models.DecimalField(decimal_places=2, help_text='Rentang 0-4, dengan dua angka di belakang koma.', max_digits=3)),
            ],
        ),
    ]
