# Generated by Django 5.1 on 2025-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_remove_user_ipk_remove_user_npm_user_golongan_darah'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_polis_asuransi',
            field=models.CharField(default=0, help_text='Nomor polis harus terdiri dari 5 hingga 10 angka.', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='golongan_darah',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Golongan darah harus berupa: A+, A-, B+, B-, O+, O-, AB+, atau AB-.', max_length=3),
        ),
    ]
